apiVersion: __API_VERSION__
kind: HorizontalPodAutoscaler
metadata:
  name: dataiku-hpa-__DKU_EXECUTION_ID__
__ANNOTATIONS__
spec:
  scaleTargetRef:
    apiVersion: __DEPLOYMENT_API_VERSION__
    kind: Deployment
    name: dataiku-exec-__DKU_EXECUTION_ID__
  minReplicas: __MIN_PODS__
  maxReplicas: __MAX_PODS__
__SCALING_CONDITION__
