apiVersion: batch/v1
kind: Job
metadata:
  name: dataiku-exec-__DKU_EXECUTION_ID__
  # __DKU_LABELS_AND_ANNOTATIONS__
  # To add labels to pods and jobs, set a dku.kubernetes.jobs.extraLabels key
  # To add annotations to pods and jobs, set a dku.kubernetes.jobs.extraAnnotations key
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    metadata:
      name: dataiku-exec
      # __DKU_LABELS_AND_ANNOTATIONS__
    spec:
      containers:
      - name: c
        image: __DKU_IMAGE_ID__
        imagePullPolicy: IfNotPresent # local image
        env:
        - name: DKU_EXECUTION_ID
          value: "__DKU_EXECUTION_ID__"
        - name: DKU_BACKEND_PORT
          value: "__DKU_BACKEND_PORT__"
        - name: DKU_BACKEND_HOST
          value: "__DKU_BACKEND_HOST__"
        - name: DKU_SERVER_PORT
          value: "__DKU_SERVER_PORT__"
        - name: DKU_SERVER_HOST
          value: "__DKU_SERVER_HOST__"
        - name: DKU_SERVER_KIND
          value: "__DKU_SERVER_KIND__"
        - name: "DKU_API_TICKET"
          valueFrom:
            secretKeyRef:
              name: dkusecret-__DKU_EXECUTION_ID__
              key: apiticket
        # __DKU_ENV__
        # __DKU_KUBERNETES_RESOURCES__
        # __DKU_KUBERNETES_HOSTPATH_VOLUME_MOUNTS__
        args: ["$(DKU_EXECUTION_ID)"]
      restartPolicy: Never
      # __DKU_KUBERNETES_HOSTPATH_HOST_VOLUMES__
      # __DKU_KUBERNETES_NODESELECTOR__
      # __DKU_KUBERNETES_AFFINITY__
      # __DKU_KUBERNETES_TOLERATIONS__
